export const HELP_TEXT = [
  "*`/bee-remind`* — scheduled reminders for this channel. Every change asks you to confirm first.",
  "",
  "*Reminders*",
  "• `list` — every reminder here, with *Edit* on each and *+ New reminder* at the bottom",
  "• `show <code>` · `remove <code>` · `run <code>` — `run` posts now, still respecting holidays and cadence",
  "• ⋮ **More actions** → **Make this a reminder** turns a message you already wrote into one",
  "",
  "*Host rotation* — the bot appends `🎙 Host: @someone`, a different person each time",
  "• `host set <code> @a @b @c` · `host clear <code>`",
  "• `host skip <code>` — moves them to the back of this lap, they still get their turn",
  "• `host next <code> @who` — puts someone up next",
  "",
  "*Holidays* — shared across every channel",
  "• `holiday add <YYYY-MM-DD>` · `holiday list` · `holiday remove <YYYY-MM-DD>`",
  "",
  "*Notes*",
  "• `--on` takes `daily` or full day names: `monday,wednesday`. Defaults to `daily`.",
  "• Times are 24-hour, Asia/Jakarta.",
  "• The rotation is shuffled, and nobody repeats until everyone has hosted. `show` has the order.",
  "• Use `\\n` in `--message` for a line break, and type `@someone` to mention them.",
].join("\n");
